name: Update dev

on:
  workflow_dispatch:

jobs:
  update-dev:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout main branch
      uses: actions/checkout@v2
      with:
        ref: main

    - name: Delete dev
      run: |
        git push origin --delete dev

    - name: Create new dev from main
      run: |
        git push origin main:refs/heads/dev
